---
- name: Play to deploy an operating system on a Raspberry
  hosts: localhost
#  connection: local
  vars: 
    dir: /usr/src
    workpath: /var/lib/libvirt/images
    mntroot: /mnt
    flashmachine: armstrong
    flashdevice: /dev/sdb
    # archsuffix: arm7vhl
    # archsuffix: aarch64
    fedora32_url: https://kojipkgs.fedoraproject.org/compose/branched/Fedora-32-20200318.n.0/compose/Server/armhfp/images/Fedora-Server-armhfp-32-20200318.n.0-sda.raw.xz
    raspbian_url: https://downloads.raspberrypi.org/raspbian_lite_latest
    lazy: true
    dd_blocksize: 524288
  tasks:
    - name: Read raw file internal partition information
      parted:
        device: "{{ flashdevice }}"
        unit: B
      delegate_to: "{{ flashmachine }}"
      register: raw_part

    - name: Read raw file internal partition information
      parted:
        device: " /var/lib/libvirt/images/2020-02-13-raspbian-buster-lite.img"
        unit: B

    - name: Remove partition number 2
      parted:
        device:  /var/lib/libvirt/images/2020-02-13-raspbian-buster-lite.img
        number: 2
        state: absent

    - name: Read raw file internal partition information
      parted:
        device: " /var/lib/libvirt/images/2020-02-13-raspbian-buster-lite.img"
        unit: B

    - fail:
    - name: Create a new primary partition the exact size of the fedora root partition
      parted:
        device: /dev/sdb
        number: 2
        state: present
        part_start: "{{ (272629759.0 + 1)/1024|int}}KiB"
        # part_end: "{{ 2773483519 | int }}B"
      delegate_to: "{{ flashmachine }}"
#    - name: Extend filesystem to cover entire disk
#      delegate_to: "{{ flashmachine }}"
#      filesystem:
#        dev: "{{ flashdevice }}2"
#        fstype: xfs
#        resizefs: yes
#        force: yes 
