---
- name: Play to deploy an operating system on a Raspberry
  hosts: localhost
  connection: local
  vars: 
    dir: /usr/src
    workpath: /var/lib/libvirt/images
    rawmnt: /mnt/raw
    bootmnt: /mnt/boot
    flashmachine: armstrong
    flashdevice: /dev/sdb
    # url: https://kojipkgs.fedoraproject.org/compose/branched/Fedora-32-20200318.n.0/compose/Server/armhfp/images/Fedora-Server-armhfp-32-20200318.n.0-sda.raw.xz
    # url: https://kojipkgs.fedoraproject.org/compose/branched/Fedora-32-20200318.n.0/compose/Server/aarch64/images/Fedora-Server-32-20200318.n.0.aarch64.raw.xz
    url: https://downloads.raspberrypi.org/raspbian_lite_latest
  tasks:
    - set_fact:
        archsuffix: arm7vhl
      when: ( url.find("armhfp") != -1 ) or ( url.find("raspbian") != -1 )
    - set_fact:
        archsuffix: aarch64
      when: url.find("aarch64") != -1

    - name: Call the roles
      include_role:
        name: "{{ role }}"
      loop:
        - image-prep
#        - armulator
#        - kernel
        - image-flash
      loop_control:
        loop_var: role
