---
- name: Play to deploy an operating system on a Raspberry
  become: true
  hosts: builders
#  connection: local
  vars: 
    dir: /usr/src
    workpath: /home/builder/src/armbuild/work
    mntroot: /mnt
    target:
      machine: flasher1
      device: /dev/sdb
    dd_blocksize: 524288
    # fedora32_url: https://kojipkgs.fedoraproject.org/compose/branched/Fedora-32-20200318.n.0/compose/Server/armhfp/images/Fedora-Server-armhfp-32-20200318.n.0-sda.raw.xz
    fedora32_url: https://kojipkgs.fedoraproject.org/compose/branched/Fedora-32-20200401.n.1/compose/Server/aarch64/images/Fedora-Server-32-20200401.n.1.aarch64.raw.xz
    raspbian_url: https://downloads.raspberrypi.org/raspbian_lite_latest
    lazy: true
  tasks:  
    - debug: var=workpath
# Set up Fedora 32
    - name: Download and prep Fedora 32
      vars:
        instruction: fetch
        requested_url: "{{ fedora32_url }}"
      include_role:
        name: arm-image
   
    - name: "Find boot and root partitions in extracted image {{ extractedfile }}"
      vars:
        instruction: partscan
        image: "{{ extractedfile }}"
      include_role:
        name: arm-image

    - name: "Mount non-lvm fedora partition"
      vars:
        instruction: mount
        image: "{{ extractedfile }}"
        mountstub: "{{ mntroot }}/fedora32/root"
        partition: "{{ root_partition.0 }}"
      include_role:
        name: arm-image
      when: lvm != true
   
    - name: "Mount lvm fedora partition"
      vars:
        image: "/dev/fedora/root"
        instruction: mount
        mountstub: "{{ mntroot }}/fedora32/root"
        partition: "{{ root_partition.0 }}"
      include_role:
        name: arm-image
      when: lvm == true

    - name: Download and prep Raspbian
      vars:
        instruction: fetch
        requested_url: "{{ raspbian_url }}"
      include_role:
        name: arm-image
   
    - name: "Find boot and root partitions in extracted image {{ extractedfile }}"
      vars:
        instruction: partscan
        image: "{{ extractedfile }}"
      include_role:
        name: arm-image

    - name: Keep partition table data about the root partition to dump to flash later
      set_fact:
        flash_root:
          image: "{{ extractedfile }}"
          partition: "{{ root_partition.0 }}"

    - name: "Mount non-lvm root partition in {{ mntroot }}/raspbian/root"
      vars:
        instruction: mount
        mountstub: "{{ mntroot }}/raspbian/root"
        image: "{{ extractedfile }}"
        partition: "{{ root_partition.0 }}"
      include_role:
        name: arm-image

    - name: Configure the fedora root filesystem
      vars:
        instruction: configure-root
        location: "{{ mntroot }}/fedora32/root"
        raspbian_location: "{{ mntroot }}/raspbian/root"
        network:
          device: eth0
          ipaddr: 192.168.1.29
          prefix: 24
          gateway: 192.168.1.1
          dns1: 8.8.8.8
          bootproto: none
      include_role:
        name: arm-image  
    - name: Unmount the root filesystems
      mount:
        path: "{{ item }}"
        state: unmounted
      loop:
        - "{{ mntroot }}/raspbian/root"

    - name: "Mount the boot partition in {{ mntroot }}/raspbian/boot"
      vars:
        instruction: mount
        mountstub: "{{ mntroot }}/raspbian/boot"
        image: "{{ extractedfile }}"
        partition: "{{ boot_partition.0 }}"
      include_role:
        name: arm-image

    - name: Keep partition table data about the boot partition to dump to flash later
      set_fact:
        flash_boot:
          image: "{{ extractedfile }}"
          partition: "{{ boot_partition.0 }}"

    - name: Keep partition table data about the master boot record to dump to flash later
      set_fact:
        flash_mbr:
          image: "{{ extractedfile }}"
          partition:
            begin: 0
            end: "{{ (flash_boot.partition.begin|int - 1) }}"
            size: "{{ flash_boot.partition.begin }}"

    - name: Perform any required changes to the boot filesystem
      vars:
        instruction: configure-boot
        location: "{{ mntroot }}/raspbian/boot"
        init: "/sbin/init"
      include_role:
        name: arm-image

    - name: Unmount the boot filesystems
      mount:
        path: "{{ item }}"
        state: unmounted
      loop:
        - "{{ mntroot }}/raspbian/boot"

    - debug: var=flash_mbr
    - debug: var=flash_boot
    - debug: var=flash_root

    - name: Write to flash
      vars:
        instruction: flash
        mbr: '{{ flash_mbr }}'
        boot: '{{ flash_boot }}'
        root: '{{ flash_root }}'
      include_role:
        name: arm-image
    - name: Unmount the root filesystems
      mount:
        path: "{{ item }}"
        state: unmounted
      loop:
        - "{{ mntroot }}/fedora32/root"

    - name: "copy the Fedora32 root filesystem as files to {{ target.machine }}"
      shell: "lvchange -a n fedora ; kpartx -d /dev/loop0"
...
