---
- name: Play to deploy an operating system on a Raspberry
  hosts: localhost
  connection: local
  vars: 
    dir: /usr/src
    workpath: /var/lib/libvirt/images
    rawmnt: /mnt/raw
    bootmnt: /mnt/boot
    flashmachine: armstrong
    flashdevice: /dev/sdb
    archsuffix: arm7vhl
    # archsuffix: aarch64
  tasks:
    - name: Download and prep Fedora 32
      vars:
        fetch: https://kojipkgs.fedoraproject.org/compose/branched/Fedora-32-20200318.n.0/compose/Server/armhfp/images/Fedora-Server-armhfp-32-20200318.n.0-sda.raw.xz
      include_role:
        name: image-prep
      when: 1 == 2

    - name: Download and prep raspbian
      vars:
        fetch: https://downloads.raspberrypi.org/raspbian_lite_latest
      include_role:
        name: image-prep


    - name: Flash the raspbian image
      vars:
        fetch: https://downloads.raspberrypi.org/raspbian_lite_latest
      include_role:
        name: image-flash
