---
# tasks file for armulator
- name: Copy over the kernels from the new system to its kernelpath in our libvirt stash
  command: "cp -uvrfp {{ bootmnt }}/. {{ kernelpath }}"
- name: Raspbian wifi configuration
  template:
    src: templates/wpa_supplicant.conf.j2
    dest: "{{ bootmnt }}/wpa_supplicant.conf"

- name: Raspbian touch ssh instruction file 
  file:
    name: "{{ bootmnt }}/sshroot"
    mode: '0700'
    state: touch
