---
- name: create a .ssh directory
  file:
    name: "{{ location }}/root/.ssh"
    mode: '0700'
    state: directory
  when: pubkey is defined

- name: create a file
  file:
    path: "{{ location }}/root/.ssh/authorized_keys"
    mode: '0600'
    state: touch
  when: pubkey is defined

- name: Set appropriate permissions on the authorized_keys file
  lineinfile:
    path: "{{ location }}/root/.ssh/authorized_keys"
    line: "{{ pubkey }}"
    state: present
  when: pubkey is defined

- name: Set root password
  lineinfile:
    path: "{{ location }}/etc/shadow"
    state: present
    line: 'root:{{ rootpasswordhash }}::0:99999:7:::'
    regexp: '^root:'
  when: rootpasswordhash is defined

- name: Permit root login via ssh
  lineinfile:
    path: "{{ location }}/etc/ssh/sshd_config"
    state: present
    line: "PermitRootLogin yes"
    regexp: '^PermitRootLogin'

- name: Replace root line in fstab
  lineinfile:
    path: "{{ location }}/etc/fstab"
    state: present
    line: "/dev/mmcblk0p2 / xfs defaults,noatime 0 0"
    regexp: '^.* / .*'

- name: Remove boot and boot/efi lines in fstab
  lineinfile:
    path: "{{ location }}/etc/fstab"
    state: absent
    regexp: '^.* /boot.*'

- name: Copy over raspbian kernel modules
  command: "cp -uvrfp {{ raspbian_location }}/lib/modules {{ location }}/usr/lib"

- name: Copy over raspbian kernel modules
  command: 'cp -uvrfp {{ raspbian_location }}/etc/modprobe.d/. {{ location }}/etc/modprobe.d/'

- name: "Deploy the {{ network.device }} network interface configuration"
  template:
    src: templates/ifcfg.j2
    dest: "{{ location }}/etc/sysconfig/network-scripts/ifcfg-{{ network.device }}"

- name: Disable the initial-setup and other unneeded services
  file:
    path: "{{ location }}/etc/systemd/system/multi-user.target.wants/{{ item }}.service"
    state: absent
  loop:
    - initial-setup
    - abrtd
    - abrt-journal-core
    - abrt-oops
    - abrt-vmcore
    - abrt-xorg
    - cups
    - nfs-client
    - vboxservice
    - vmtoolsd
    - ModemManager
    - rngd
    - avahi-daemon
    - auditd
    - smartd
    - libvirtd
    - remote-fs

# - fix up /etc/fstab
...

