---
# tasks file for image-flash

# using {{ dd_blocksize }} blocks (tested with 512K blocks represented numerically as 524288)
# {{ mbr }}, {{ boot }} and {{ root }} have the following structure
# mbr|boot|root:
#   image: path to image file
#   partition:
#     begin: first byte (represented with one digit past decimal point. must be run through int for seeks and additive math.)
#     end: last byte (represented with one digit past decimal point. must be run through int for seeks and additive math.)
#     size: size in bytes (represented with one digit past decimal point. must be run through int for seeks and additive math.)
# note
#
# due to addressging starting at zero, begin and size will be even and dividable by blocksize to convert to a blocks figure.
# end will be odd and requires 1 be added to it before dividing by blocksize to be converted to a blocks figure.
- name: Display parameters provided
  debug:
    var: "{{ item }}"
  loop:
    - mbr
    - boot
    - root
    - dd_blocksize
    - target

- name: Wipe out the first 300MB of the target disk to avoid parted complaints
  delegate_to: "{{ targetmachine }}"
  become: true
  shell: "dd if=/dev/zero of={{ targetdevice }} bs=1M count=300"
 
# - name: isolate the mbr to a separate file
#  shell: "dd if={{ mbr.image }} bs={{ dd_blocksize }} count={{ (mbr.partition.size|int/dd_blocksize)|int }} of={{ mbr.image }}.mbr"

- name: "stream the mbr and boot images to {{ targetmachine }} and dd them to {{ targetdevice }}"
  shell: '( dd if={{ mbr.image }} count={{ (mbr.partition.size|int/dd_blocksize)|int }} bs={{ dd_blocksize }}; dd if={{ boot.image }} bs={{ dd_blocksize }} skip={{ (boot.partition.begin|int/dd_blocksize)|int }} count={{ (boot.partition.size|int/dd_blocksize)|int }} ) | ssh root@{{ targetmachine }} dd of={{ targetdevice }} bs={{ dd_blocksize }}'

- name: "Remove partition 2 on {{ targetdevice }} on {{ targetmachine }}"
  delegate_to: "{{ targetmachine }}"
  become: true
  parted:
    device: "{{ targetdevice }}"
    number: 2
    state: absent

- name: Create a new root partition on {{ targetdevice }} on {{ targetmachine }}"
  delegate_to: "{{ targetmachine }}"
  become: true
  parted:
    device: "{{ targetdevice }}"
    number: 2
    state: present
    part_start: "{{ ((mbr.partition.size|int + boot.partition.size|int)|int/1024)|int }}KiB"

- name: "Create a filesystem on partition {{ targetdevice }}2 on {{ targetmachine }}"
  delegate_to: "{{ targetmachine }}"
  become: true
  filesystem:
    dev: "{{ targetdevice }}2"
    fstype: ext4

- name: make sure local mount stubs exist
  delegate_to: "{{ targetmachine }}"
  become: true
  file:
    name: "{{ mntroot }}/piroot"
    mode: '0700'
    state: directory

- name: "mount {{ targetdevice }}2 on {{ targetmachine }}"
  delegate_to: "{{ targetmachine }}"
  become: true
  mount:
    src: "{{ targetdevice }}2"
    path: "{{ mntroot }}/piroot"
    state: mounted
    fstab: /tmp/fstab.dummy
    fstype: ext4

- name: "copy the Fedora32 root filesystem as files to {{ targetdevice }}2 on {{ targetmachine }}"
  shell: "tar cfp - . | ssh root@{{ targetmachine }} 'cd {{ mntroot }}/piroot; tar xvfp -'"
  args:
    chdir: "{{ mntroot }}/fedora32/root"
    warn: no

- name: "chmod the / directory inside {{ targetdevice }}2 on {{ targetmachine }}"
  delegate_to: "{{ targetmachine }}"
  become: true
  file:
    path: "{{ mntroot }}/piroot"
    state: directory
    mode: '0755'

- name: Unmount the remote target filesystem
  delegate_to: "{{ targetmachine }}"
  become: true
  mount:
    path: "{{ mntroot }}/piroot"
    state: unmounted
