---
# tasks file for armulator
- set_fact:
    partflags: []
    lvm: ""

- name: Read device information (always use unit when probing)
  parted:
    device: "{{ extractedfile }}"
    unit: B
  register: raw_part

- debug: var=raw_part.partitions

- name: Concatenate partition flags to check if there are lvm ones
  set_fact:
    partflags: "{{ partflags + item.flags }}"
  loop: "{{ raw_part.partitions }}"

- name: Enable lvm handling if an lvm flag is found
  set_fact:
    lvm: true
  loop: "{{ partflags }}"
  when: item == "lvm"

- name: Select the main partition
  set_fact:
    root_partition:
      - "{{ raw_part.partitions|last }}"
  when: lvm != true

- name: Set the rootpart if fedora aarch64 lvm is used
  set_fact:
    root_partition:
      - "/dev/fedora/root"
  when: lvm == true

- set_fact:
    remaining_parts: "{{ raw_part.partitions | difference( root_partition ) }}"

- set_fact:
    boot_partition: 
      - "{{ remaining_parts|last }}"
